apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "taskboard.selectorLabels" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
