apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taskboard.selectorLabels" (dict "root" . "component" "backend") | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "taskboard.selectorLabels" (dict "root" . "component" "backend") | nindent 8 }}
      annotations:
        # roll pods when config/secret change
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          image: {{ include "taskboard.backendImage" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "taskboard.fullname" . }}-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskboard.secretName" . }}
                  key: DATABASE_URL
          startupProbe:
            httpGet:
              path: {{ .Values.backend.probes.startup.path }}
              port: http
            periodSeconds: {{ .Values.backend.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: http
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: http
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.backend.containerSecurityContext | nindent 12 }}
