{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    {{- toYaml .Values.monitoring.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "taskboard.selectorLabels" (dict "root" . "component" "backend") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
