apiVersion: v1
kind: Service
metadata:
  name: session17-devsecops-api
spec:
  type: NodePort
  selector:
    app: session17-devsecops-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
