apiVersion: v1
kind: Service
metadata:
  name: web-rolling
  namespace: s10
  labels:
    app: web-rolling
spec:
  type: NodePort
  selector:
    app: web-rolling
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30010
      protocol: TCP
