apiVersion: v1
kind: Service
metadata:
  name: session16-calculator-api
spec:
  type: ClusterIP
  selector:
    app: session16-calculator-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
