apiVersion: v1
kind: Service
metadata:
  name: web-recreate
  namespace: s10
  labels:
    app: web-recreate
spec:
  type: NodePort
  selector:
    app: web-recreate
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30040
      protocol: TCP
